### ISSUE TITLE
Open source Flux

### ISSUE THREAD

**Issue by gilesvangruisen** [thoughtbot/Delta#8]
Checklist before quietly open sourcing flux:
- [ ] Decent cursory documentation https://github.com/thoughtbot/Flux/issues/16
- [x] Reduce setup (see #4) perhaps it wouldn't hurt to get some outside perspective
- [ ] More thorough testing, switch to Quick/Nimble? https://github.com/thoughtbot/Flux/issues/9
